### ISSUE TITLE
Counties with Two Word Names

### ISSUE THREAD

**Issue by cmarkymark** [wpinvestigative/arcos#1]
Hello!

First, this library is super helpful!!

So I noticed when I attempt to search for a county with a two word name (ie "San Diego"), it throws a 502 error.  When I use a single word county name, it runs fine.  Was wondering if this has come up before?

Thanks

Charles

**Comment by andrewbtran** [comment]
Thanks for letting us know. I've pushed out a new version that handles the spaces correctly.

**Comment by cmarkymark** [comment]
Awesome!  A potential suggestion, if there was a function that just returned a data.frame of all of the counties and states (as stored in your db), that would make certain automations easier to set up.  Anyway, thanks for this library once again!
