### ISSUE TITLE
Incorrectly geocoded addresses in pharm_latlon

### ISSUE THREAD

**Issue by angela-li** [wpinvestigative/arcos#3]
There are 9 pharmacies in Illinois that are incorrectly geocoded (ie, they do not fall within the IL state boundaries), with the following DEA numbers: 

  BUYER_DEA_NO BUYER_STATE BUYER_COUNTY                  geometry
1    BA6075988          IL      MADISON POINT (-117.1265 32.8221)
2    BW2139182          IL         CASS POINT (-121.4812 38.5887)
3    BC4206543          IL   JO DAVIESS  POINT (-92.0257 42.1674)
4    BD5886835          IL       DUPAGE   POINT (-95.6316 37.037)
5    BH7884302          IL     TAZEWELL  POINT (-90.4093 38.6743)
6    BP8902416          IL    VERMILION  POINT (-74.5438 40.4081)
7    BM5197618          IL    JEFFERSON  POINT (-73.8874 40.8434)
8    FC1086114          IL         COOK  POINT (-73.9549 40.8197)
9    AS9202463          IL     WOODFORD   POINT (-97.2246 33.004)

**Comment by angela-li** [comment]
I'm testing out some other states, and this appears to be a problem in more than just Illinois - many pharmacies are geocoded incorrectly, in that `pharm_latlon` returns points that fall out of a state boundary, see the following map for Florida, which shows 11 incorrectly geocoded points. 

![image](https://user-images.githubusercontent.com/15808896/68628818-56c4a980-04a7-11ea-93ac-789a8e92d85e.png)

**Comment by andrewbtran** [comment]
I think this has been fixed. Thanks!
