### ISSUE TITLE
raw_data delimiter

### ISSUE THREAD

**Issue by staceybrandsma** [wpinvestigative/arcos#4]
I'm trying to use the raw_data(key = 'WaPo') function and I keep getting an error:

![image](https://user-images.githubusercontent.com/40171228/73665830-c3e37780-466f-11ea-8a9d-4c1dcac8ebd3.png)

Any advice?  Thanks!

**Comment by jeffcsauer** [comment]
Hi @staceybrandsma, 

Could you please post a bit more of your code so we could see what is going on? 

Please provide the following:
```r
sessionInfo()
packageVersion("arcos")
```

I attempted the function today and it seems to be working:
```r
> arcos::raw_data(key = "WaPo") 
indexed 53.21MB 0s in  4s, 14.25MB/s
```

**Comment by andrewbtran** [comment]
Thanks, having some real issues with this file thanks to its size. Trying to come up with a different method, perhaps load year by year until there's no space on the user's computer.
