### ISSUE TITLE
[DOC] Suggestion on renaming 'Articles' menu button of arcos site

### ISSUE THREAD

**Issue by jeffcsauer** [wpinvestigative/arcos#7]
Following a point raised during [the JOSS review process](https://github.com/openjournals/joss-reviews/issues/2450), a suggestion was made that the menu navigation button 'Articles' be renamed to something more explicit (on the https://wpinvestigative.github.io/arcos site). 

Potential renames:

- User Guides
- Walkthroughts
- Examples
- Vignettes

or others!

**Comment by andrewbtran** [comment]
Doing a mini revamp of this so I can update the language on the tabs in a week or two.

**Comment by andrewbtran** [comment]
Has been renamed [Walkthroughs](https://wpinvestigative.github.io/arcos/).
